### ISSUE TITLE
Exception in case of Error

### ISSUE THREAD

**Issue by aravindavk** [ettomatic/xattr#1]
Sample program, where File is not found.

```crystal
require "xattr"
xattr = XAttr.new(ARGV[0])
puts xattr.keys
```

Run using,

```console
$ shards build
$ ./bin/xattrtest nonexisting.txt
[]
```

If I print error number then it is properly set.

```
require "xattr"
xattr = XAttr.new(ARGV[0])
puts xattr.keys
puts Errno.value
```

```console
$ ./bin/xattrtest nonexisting.txt
[]
ENOENT
```

Please raise exceptions in case of failures. Like this https://github.com/crystal-lang/crystal/blob/5999ae29b/src/file/error.cr#L8

From the `libxattr` man page(Mac)

> On success, the size of the extended attribute name list is returned.  If no accessible extended attributes are associated with the given path or fd, the function returns zero.  On failure, -1 is returned and the global variable errno is set as follows.

**Comment by ettomatic** [comment]
yep, I'll need to fix this as it's only raising an exception for setters:
https://github.com/ettomatic/xattr/blob/master/src/xattr/xattr.cr#L20

Thanks for reporting

**Comment by aravindavk** [comment]
As suggested, Sent PR to add `raise_error` call to get and list calls. Please review

https://github.com/ettomatic/xattr/pull/2
